"""Add guild_settings table

Revision ID: 6f841171f991
Revises: 9e731ff771f0
Create Date: 2026-05-15 19:11:54.129616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f841171f991'
down_revision: Union[str, Sequence[str], None] = '9e731ff771f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_settings')
    # ### end Alembic commands ###
